# Generated by Django 3.0.4 on 2020-07-05 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200704_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='user_puntuation',
            options={'verbose_name': 'Puntuation', 'verbose_name_plural': 'Puntuations'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='user_puntuation',
            name='evaluated_id',
        ),
        migrations.RemoveField(
            model_name='user_puntuation',
            name='evaluator_id',
        ),
        migrations.RemoveField(
            model_name='user_puntuation',
            name='puntuation',
        ),
        migrations.AddField(
            model_name='category',
            name='category_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_puntuation',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comentario'),
        ),
        migrations.AddField(
            model_name='user_puntuation',
            name='evaluated_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluated_user', to=settings.AUTH_USER_MODEL, verbose_name='Evaluado'),
        ),
        migrations.AddField(
            model_name='user_puntuation',
            name='evaluator_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_user', to=settings.AUTH_USER_MODEL, verbose_name='Evaluador'),
        ),
        migrations.AddField(
            model_name='user_puntuation',
            name='points',
            field=models.IntegerField(null=True, verbose_name='Puntos'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_method_order', to='api.Payment_method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shipping_method_order', to='api.Shipping_method'),
        ),
        migrations.AlterField(
            model_name='payment_data',
            name='payment_method_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_method', to='api.Payment_method'),
        ),
        migrations.AlterField(
            model_name='user_puntuation',
            name='follow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
